/* Automatically generated by './build/bin/build-entry.js' */
'use strict'
// 所有组件
import Alert from '../packages/alert/index.js'
import Aside from '../packages/aside/index.js'
import Autocomplete from '../packages/autocomplete/index.js'
import Badge from '../packages/badge/index.js'
import BreadcrumbItem from '../packages/breadcrumb-item/index.js'
import Breadcrumb from '../packages/breadcrumb/index.js'
import ButtonGroup from '../packages/button-group/index.js'
import Button from '../packages/button/index.js'
import Card from '../packages/card/index.js'
import CarouselItem from '../packages/carousel-item/index.js'
import Carousel from '../packages/carousel/index.js'
import Cascader from '../packages/cascader/index.js'
import CheckboxButton from '../packages/checkbox-button/index.js'
import CheckboxGroup from '../packages/checkbox-group/index.js'
import Checkbox from '../packages/checkbox/index.js'
import Col from '../packages/col/index.js'
import CollapseItem from '../packages/collapse-item/index.js'
import CollapseTransition from '../packages/collapse-transition/index.js'
import Collapse from '../packages/collapse/index.js'
import ColorPicker from '../packages/color-picker/index.js'
import Container from '../packages/container/index.js'
import DatePicker from '../packages/date-picker/index.js'
import Dialog from '../packages/dialog/index.js'
import DropdownItem from '../packages/dropdown-item/index.js'
import DropdownMenu from '../packages/dropdown-menu/index.js'
import Dropdown from '../packages/dropdown/index.js'
import Footer from '../packages/footer/index.js'
import FormItem from '../packages/form-item/index.js'
import Form from '../packages/form/index.js'
import Header from '../packages/header/index.js'
import Icon from '../packages/icon/index.js'
import InputNumber from '../packages/input-number/index.js'
import Input from '../packages/input/index.js'
import IntegratedPage from '../packages/integrated-page/index.js'
import Loading from '../packages/loading/index.js'
import Main from '../packages/main/index.js'
import MenuItemGroup from '../packages/menu-item-group/index.js'
import MenuItem from '../packages/menu-item/index.js'
import Menu from '../packages/menu/index.js'
import MessageBox from '../packages/message-box/index.js'
import Message from '../packages/message/index.js'
import NavMenu from '../packages/nav-menu/index.js'
import Notification from '../packages/notification/index.js'
import OptionGroup from '../packages/option-group/index.js'
import Option from '../packages/option/index.js'
import Pagination from '../packages/pagination/index.js'
import Popover from '../packages/popover/index.js'
import Progress from '../packages/progress/index.js'
import QueryConditions from '../packages/query-conditions/index.js'
import RadioButton from '../packages/radio-button/index.js'
import RadioGroup from '../packages/radio-group/index.js'
import Radio from '../packages/radio/index.js'
import Rate from '../packages/rate/index.js'
import RoutesTree from '../packages/routes-tree/index.js'
import Row from '../packages/row/index.js'
import Scrollbar from '../packages/scrollbar/index.js'
import Select from '../packages/select/index.js'
import Slider from '../packages/slider/index.js'
import Spinner from '../packages/spinner/index.js'
import Step from '../packages/step/index.js'
import Steps from '../packages/steps/index.js'
import Submenu from '../packages/submenu/index.js'
import Switch from '../packages/switch/index.js'
import TabPane from '../packages/tab-pane/index.js'
import Table from '../packages/table/index.js'
import TabsView from '../packages/tabs-view/index.js'
import Tabs from '../packages/tabs/index.js'
import Tag from '../packages/tag/index.js'
import TimePicker from '../packages/time-picker/index.js'
import TimeSelect from '../packages/time-select/index.js'
import Tooltip from '../packages/tooltip/index.js'
import Transfer from '../packages/transfer/index.js'
import Tree from '../packages/tree/index.js'
import Upload from '../packages/upload/index.js'
// 国际化支持
import {locale, i18n} from 'element-ui'
// ajax支持
import ajax from './utils/ajax'
// 样式支持
import './css/index.scss'
// Promise兼容支持
import Promise from 'bluebird'
// 默认标签页路由解析器
import routesProcessor from './utils/routes-processor'
// 日期工具函数
import DateUtils from './utils/date-util'
// 字符串工具函数
import StringUtils from './utils/string-util'
// 类型检测工具函数
import TypeCheck from './utils/type-check'
// 表单校验规则生成工具
import ValidateRules from './utils/validate-rules'

const Locale = {locale, i18n}
const $ajax = ajax

const components = [
  Alert,
  Aside,
  Autocomplete,
  Badge,
  BreadcrumbItem,
  Breadcrumb,
  ButtonGroup,
  Button,
  Card,
  CarouselItem,
  Carousel,
  Cascader,
  CheckboxButton,
  CheckboxGroup,
  Checkbox,
  Col,
  CollapseItem,
  CollapseTransition,
  Collapse,
  ColorPicker,
  Container,
  DatePicker,
  Dialog,
  DropdownItem,
  DropdownMenu,
  Dropdown,
  Footer,
  FormItem,
  Form,
  Header,
  Icon,
  InputNumber,
  Input,
  IntegratedPage,
  Main,
  MenuItemGroup,
  MenuItem,
  Menu,
  NavMenu,
  OptionGroup,
  Option,
  Pagination,
  Popover,
  Progress,
  QueryConditions,
  RadioButton,
  RadioGroup,
  Radio,
  Rate,
  RoutesTree,
  Row,
  Scrollbar,
  Select,
  Slider,
  Spinner,
  Step,
  Steps,
  Submenu,
  Switch,
  TabPane,
  Table,
  Tabs,
  Tag,
  TimePicker,
  TimeSelect,
  Tooltip,
  Transfer,
  Tree,
  Upload
]

const install = function (Vue, {size = '', zIndex = 2000, locale, i18n} = {}) {
  Locale.locale(locale)
  Locale.i18n(i18n)

  components.map(component => {
    Vue.use(component)
  })

  Vue.use(Loading.directive)

  Vue.prototype.$ELEMENT = {
    size: size,
    zIndex: zIndex
  }

  Vue.prototype.$ajax = ajax
  Vue.prototype.$loading = Loading.service
  Vue.prototype.$msgbox = MessageBox
  Vue.prototype.$alert = MessageBox.alert
  Vue.prototype.$confirm = MessageBox.confirm
  Vue.prototype.$prompt = MessageBox.prompt
  Vue.prototype.$notify = Notification
  Vue.prototype.$message = Message
}

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

/* unify Promise */
if (typeof window !== 'undefined') {
  window.Promise = Promise
}

export {
  locale,
  i18n,
  install,
  ajax,
  $ajax,
  Promise,
  routesProcessor,
  DateUtils,
  StringUtils,
  TypeCheck,
  ValidateRules,
  Alert,
  Aside,
  Autocomplete,
  Badge,
  BreadcrumbItem,
  Breadcrumb,
  ButtonGroup,
  Button,
  Card,
  CarouselItem,
  Carousel,
  Cascader,
  CheckboxButton,
  CheckboxGroup,
  Checkbox,
  Col,
  CollapseItem,
  CollapseTransition,
  Collapse,
  ColorPicker,
  Container,
  DatePicker,
  Dialog,
  DropdownItem,
  DropdownMenu,
  Dropdown,
  Footer,
  FormItem,
  Form,
  Header,
  Icon,
  InputNumber,
  Input,
  IntegratedPage,
  Loading,
  Main,
  MenuItemGroup,
  MenuItem,
  Menu,
  MessageBox,
  Message,
  NavMenu,
  Notification,
  OptionGroup,
  Option,
  Pagination,
  Popover,
  Progress,
  QueryConditions,
  RadioButton,
  RadioGroup,
  Radio,
  Rate,
  RoutesTree,
  Row,
  Scrollbar,
  Select,
  Slider,
  Spinner,
  Step,
  Steps,
  Submenu,
  Switch,
  TabPane,
  Table,
  TabsView,
  Tabs,
  Tag,
  TimePicker,
  TimeSelect,
  Tooltip,
  Transfer,
  Tree,
  Upload
}

export default {
  version: '0.0.4',
  locale,
  i18n,
  install,
  ajax,
  $ajax,
  Promise,
  routesProcessor,
  DateUtils,
  StringUtils,
  TypeCheck,
  ValidateRules,
  Alert,
  Aside,
  Autocomplete,
  Badge,
  BreadcrumbItem,
  Breadcrumb,
  ButtonGroup,
  Button,
  Card,
  CarouselItem,
  Carousel,
  Cascader,
  CheckboxButton,
  CheckboxGroup,
  Checkbox,
  Col,
  CollapseItem,
  CollapseTransition,
  Collapse,
  ColorPicker,
  Container,
  DatePicker,
  Dialog,
  DropdownItem,
  DropdownMenu,
  Dropdown,
  Footer,
  FormItem,
  Form,
  Header,
  Icon,
  InputNumber,
  Input,
  IntegratedPage,
  Loading,
  Main,
  MenuItemGroup,
  MenuItem,
  Menu,
  MessageBox,
  Message,
  NavMenu,
  Notification,
  OptionGroup,
  Option,
  Pagination,
  Popover,
  Progress,
  QueryConditions,
  RadioButton,
  RadioGroup,
  Radio,
  Rate,
  RoutesTree,
  Row,
  Scrollbar,
  Select,
  Slider,
  Spinner,
  Step,
  Steps,
  Submenu,
  Switch,
  TabPane,
  Table,
  TabsView,
  Tabs,
  Tag,
  TimePicker,
  TimeSelect,
  Tooltip,
  Transfer,
  Tree,
  Upload
}
